# Generated by Django 5.0.14 on 2025-10-25 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cms", "0041_alter_pageurl_unique_together_pageurl_site_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroBannerPlugin",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.TextField(blank=True)),
                ("background_image", models.ImageField(upload_to="hero_banners/")),
                ("cta_text", models.CharField(blank=True, max_length=100)),
                ("cta_link", models.URLField(blank=True)),
            ],
            bases=("cms.cmsplugin",),
        ),
    ]
