# Generated by Django 5.0.14 on 2025-10-25 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_plugins", "0002_announcement_featuredannouncementsplugin"),
    ]

    operations = [
        migrations.AddField(
            model_name="herobannerplugin",
            name="height",
            field=models.PositiveIntegerField(
                default=400, help_text="Height in pixels"
            ),
        ),
        migrations.AddField(
            model_name="herobannerplugin",
            name="width",
            field=models.PositiveIntegerField(
                default=1200, help_text="Width in pixels"
            ),
        ),
    ]
