# Generated by Django 5.0.14 on 2025-10-25 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_plugins", "0003_herobannerplugin_height_herobannerplugin_width"),
    ]

    operations = [
        migrations.AddField(
            model_name="herobannerplugin",
            name="background_color",
            field=models.CharField(
                default="#ffffff",
                help_text="Background color in hex format (e.g., #ffffff)",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="herobannerplugin",
            name="font_size",
            field=models.PositiveIntegerField(
                default=16, help_text="Font size in pixels"
            ),
        ),
        migrations.AddField(
            model_name="herobannerplugin",
            name="text_color",
            field=models.CharField(
                default="#000000",
                help_text="Text color in hex format (e.g., #000000)",
                max_length=7,
            ),
        ),
    ]
