# Generated by Django 5.0.14 on 2025-10-25 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0041_alter_pageurl_unique_together_pageurl_site_and_more"),
        ("cms_plugins", "0007_quicklinksplugin_quicklinkitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatisticsCounterPlugin",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
            ],
            bases=("cms.cmsplugin",),
        ),
        migrations.CreateModel(
            name="StatisticsCounterItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("value", models.PositiveIntegerField()),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Optional icon class (e.g., 'fa fa-users')",
                        max_length=50,
                    ),
                ),
                (
                    "statistics_counter_plugin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cms_plugins.statisticscounterplugin",
                    ),
                ),
            ],
            options={
                "verbose_name": "Statistics Counter Item",
                "verbose_name_plural": "Statistics Counter Items",
                "ordering": ["pk"],
            },
        ),
    ]
