# Generated by Django 5.0.14 on 2025-10-25 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0041_alter_pageurl_unique_together_pageurl_site_and_more"),
        ("cms_plugins", "0008_statisticscounterplugin_statisticscounteritem"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestimonialPlugin",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
            ],
            bases=("cms.cmsplugin",),
        ),
        migrations.CreateModel(
            name="TestimonialItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("photo", models.ImageField(blank=True, upload_to="testimonials/")),
                ("course", models.CharField(blank=True, max_length=100)),
                ("testimonial", models.TextField()),
                (
                    "testimonial_plugin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cms_plugins.testimonialplugin",
                    ),
                ),
            ],
            options={
                "verbose_name": "Testimonial Item",
                "verbose_name_plural": "Testimonial Items",
                "ordering": ["pk"],
            },
        ),
    ]
