# Generated by Django 5.0.14 on 2025-10-25 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0041_alter_pageurl_unique_together_pageurl_site_and_more"),
        ("cms_plugins", "0009_testimonialplugin_testimonialitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="CTABannerPlugin",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                ("heading", models.CharField(max_length=200)),
                ("subheading", models.TextField(blank=True)),
                ("cta_text", models.CharField(blank=True, max_length=100)),
                ("cta_link", models.URLField(blank=True)),
                (
                    "background_image",
                    models.ImageField(blank=True, upload_to="cta_banners/"),
                ),
            ],
            bases=("cms.cmsplugin",),
        ),
    ]
