# Generated by Django 5.0.14 on 2025-10-25 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_plugins", "0010_ctabannerplugin"),
    ]

    operations = [
        migrations.AddField(
            model_name="herobannerplugin",
            name="background_video",
            field=models.FileField(
                blank=True,
                help_text="MP4 format recommended",
                upload_to="hero_banners/",
            ),
        ),
        migrations.AddField(
            model_name="herobannerplugin",
            name="overlay_color",
            field=models.CharField(
                default="#000000",
                help_text="Overlay color in hex format (e.g., #000000)",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="herobannerplugin",
            name="overlay_opacity",
            field=models.DecimalField(
                decimal_places=2,
                default=0.8,
                help_text="Overlay opacity (0.0 to 1.0)",
                max_digits=3,
            ),
        ),
        migrations.AlterField(
            model_name="herobannerplugin",
            name="background_image",
            field=models.ImageField(blank=True, upload_to="hero_banners/"),
        ),
    ]
