# Generated by Django 5.0.14 on 2025-10-25 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_plugins", "0011_herobannerplugin_background_video_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="featuredannouncementsplugin",
            name="enable_carousel",
            field=models.BooleanField(
                default=True, help_text="Enable carousel view for announcements"
            ),
        ),
    ]
