# Generated by Django 5.0.14 on 2025-10-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_plugins", "0012_featuredannouncementsplugin_enable_carousel"),
    ]

    operations = [
        migrations.AddField(
            model_name="upcomingeventsplugin",
            name="auto_rotate",
            field=models.BooleanField(
                default=True,
                help_text="Enable automatic rotation of events in carousel",
            ),
        ),
        migrations.AddField(
            model_name="upcomingeventsplugin",
            name="enable_carousel",
            field=models.BooleanField(
                default=True, help_text="Enable carousel view for events"
            ),
        ),
        migrations.AddField(
            model_name="upcomingeventsplugin",
            name="rotation_interval",
            field=models.PositiveIntegerField(
                default=5000,
                help_text="Rotation interval in milliseconds (minimum 1000)",
            ),
        ),
    ]
