# Generated by Django 5.0.14 on 2025-10-25 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_plugins", "0013_upcomingeventsplugin_auto_rotate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="welcomesectionplugin",
            name="cta_link",
            field=models.URLField(
                blank=True, help_text="URL for the call-to-action button"
            ),
        ),
        migrations.AddField(
            model_name="welcomesectionplugin",
            name="cta_text",
            field=models.CharField(
                blank=True,
                help_text="Text for the call-to-action button",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="welcomesectionplugin",
            name="image_alignment",
            field=models.CharField(
                choices=[
                    ("left", "Left"),
                    ("right", "Right"),
                    ("background", "Full-width Background"),
                ],
                default="right",
                help_text="Select image alignment",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="welcomesectionplugin",
            name="content",
            field=models.TextField(help_text="Supports HTML formatting"),
        ),
    ]
