# Generated by Django 5.0.14 on 2025-10-25 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_plugins", "0014_welcomesectionplugin_cta_link_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quicklinkitem",
            options={
                "ordering": ["order"],
                "verbose_name": "Quick Link Item",
                "verbose_name_plural": "Quick Link Items",
            },
        ),
        migrations.AddField(
            model_name="quicklinkitem",
            name="background_color",
            field=models.CharField(
                default="#ffffff",
                help_text="Background color in hex format (e.g., #ffffff)",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="quicklinkitem",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Order of the link in the plugin"
            ),
        ),
    ]
