# Generated by Django 5.0.14 on 2025-10-25 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_plugins", "0015_alter_quicklinkitem_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonialitem",
            name="is_featured",
            field=models.BooleanField(
                default=False, help_text="Highlight this testimonial"
            ),
        ),
    ]
