# Generated by Django 5.0.14 on 2025-10-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_plugins", "0016_testimonialitem_is_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="ctabannerplugin",
            name="background_color",
            field=models.CharField(
                default="#007bff",
                help_text="Background color in hex format (e.g., #007bff)",
                max_length=7,
            ),
        ),
    ]
