# Generated by Django 5.0.14 on 2025-10-25 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0041_alter_pageurl_unique_together_pageurl_site_and_more"),
        ("cms_plugins", "0017_ctabannerplugin_background_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("science", "Science"),
                            ("arts", "Arts"),
                            ("business", "Business"),
                            ("technology", "Technology"),
                        ],
                        default="science",
                        max_length=20,
                    ),
                ),
                ("instructor", models.CharField(max_length=100)),
                ("credits", models.PositiveIntegerField(default=3)),
                (
                    "duration",
                    models.CharField(
                        help_text="e.g., '15 weeks', '8 weeks'", max_length=50
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="CourseSearchPlugin",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                ("title", models.CharField(default="Course Search", max_length=200)),
                (
                    "placeholder_text",
                    models.CharField(
                        default="Search courses by title, code, description, or instructor...",
                        max_length=200,
                    ),
                ),
            ],
            bases=("cms.cmsplugin",),
        ),
        migrations.AddField(
            model_name="event",
            name="category",
            field=models.CharField(
                choices=[
                    ("academic", "Academic"),
                    ("sports", "Sports"),
                    ("cultural", "Cultural"),
                    ("social", "Social"),
                    ("administrative", "Administrative"),
                ],
                default="academic",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="upcomingeventsplugin",
            name="show_category_filter",
            field=models.BooleanField(
                default=True, help_text="Show category filter dropdown"
            ),
        ),
        migrations.AddField(
            model_name="upcomingeventsplugin",
            name="show_date_filter",
            field=models.BooleanField(
                default=True, help_text="Show date filter dropdown"
            ),
        ),
    ]
