# Generated by Django 5.0.14 on 2025-10-25 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0041_alter_pageurl_unique_together_pageurl_site_and_more"),
        ("cms_plugins", "0018_course_coursesearchplugin_event_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NavbarItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        help_text="URL for the menu item (leave blank for dropdown)",
                        max_length=200,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order of the item in the navbar"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, help_text="Mark as active item"),
                ),
            ],
            options={
                "verbose_name": "Navbar Item",
                "verbose_name_plural": "Navbar Items",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="NavbarPlugin",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                (
                    "brand_text",
                    models.CharField(
                        default="Student Management System", max_length=200
                    ),
                ),
                (
                    "brand_link",
                    models.CharField(
                        default="/",
                        help_text="URL for the brand/logo link",
                        max_length=200,
                    ),
                ),
            ],
            bases=("cms.cmsplugin",),
        ),
        migrations.CreateModel(
            name="NavbarItemChild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("url", models.CharField(max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cms_plugins.navbaritem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Navbar Child Item",
                "verbose_name_plural": "Navbar Child Items",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="navbaritem",
            name="navbar_plugin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cms_plugins.navbarplugin",
            ),
        ),
    ]
