# Generated by Django 5.0.14 on 2025-10-25 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0041_alter_pageurl_unique_together_pageurl_site_and_more"),
        (
            "cms_plugins",
            "0020_student_studentdashboardplugin_grade_enrollment_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveNotificationsPlugin",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                ("title", models.CharField(default="Notifications", max_length=200)),
            ],
            bases=("cms.cmsplugin",),
        ),
        migrations.CreateModel(
            name="LiveNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("announcement", "New Announcement"),
                            ("grade", "Grade Released"),
                            ("event", "Event Reminder"),
                            ("system", "System Notification"),
                        ],
                        default="system",
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Live Notification",
                "verbose_name_plural": "Live Notifications",
                "ordering": ["-timestamp"],
            },
        ),
    ]
