# Generated by Django 5.0.14 on 2025-10-25 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0041_alter_pageurl_unique_together_pageurl_site_and_more"),
        ("cms_plugins", "0021_livenotificationsplugin_livenotification"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerformanceAnalyticsPlugin",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="Performance Analytics", max_length=200),
                ),
                (
                    "default_time_range",
                    models.CharField(
                        choices=[
                            ("week", "Weekly"),
                            ("month", "Monthly"),
                            ("semester", "Semester"),
                        ],
                        default="month",
                        help_text="Default time range for analytics",
                        max_length=10,
                    ),
                ),
            ],
            bases=("cms.cmsplugin",),
        ),
    ]
