# Generated by Django 5.0.14 on 2025-10-25 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0041_alter_pageurl_unique_together_pageurl_site_and_more"),
        ("cms_plugins", "0022_performanceanalyticsplugin"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyRecommendationPlugin",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Recommended Study Materials", max_length=200
                    ),
                ),
                (
                    "number_of_recommendations",
                    models.PositiveIntegerField(
                        choices=[
                            (3, "3 Recommendations"),
                            (5, "5 Recommendations"),
                            (10, "10 Recommendations"),
                        ],
                        default=5,
                        help_text="Number of recommendations to display",
                    ),
                ),
            ],
            bases=("cms.cmsplugin",),
        ),
        migrations.CreateModel(
            name="AttendanceTrackerPlugin",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="Attendance Tracker", max_length=200),
                ),
                (
                    "date",
                    models.DateField(help_text="Date for which to track attendance"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        help_text="Select a course to track attendance for. If none selected, shows all courses.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cms_plugins.course",
                    ),
                ),
            ],
            bases=("cms.cmsplugin",),
        ),
    ]
